[repository]
repository = "rclone:mega-backups:"
password-file = "/home/giuseppe/.config/rustic/rustic-key"

[backup]
glob-file = "/home/giuseppe/.config/rustic/excludes.txt"
git-ignore = true

[[backup.sources]]
source = "/home/giuseppe/Documents/"

[forget]
keep-daily = 7
keep-weekly = 4
keep-monthly = 3
prune = true
