[repository]
repository = "rclone:mega-backups:"
password-file = "/home/giuseppe/.config/rustic/rustic-key"

[backup]
git-ignore = true
glob-files = ["/home/giuseppe/.config/rustic/excludes.txt"]

[[backup.snapshots]]
sources = ["/home/giuseppe/Documents/"]

[forget]
keep-daily = 7
keep-weekly = 4
keep-monthly = 3
