"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$hostname$directory$character"""

right_format = """$git_branch$python"""

[hostname]
ssh_only = true
ssh_symbol = "󰣀 "
format = '[$ssh_symbol](bold blue) [$hostname](bold red) '

[directory]
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vimcmd_symbol = '[V](bold teal)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
